# Generated by Django 5.2.4 on 2025-11-16 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='genres/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='artists/profiles/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='artists/covers/')),
                ('is_verified', models.BooleanField(default=False)),
                ('monthly_listeners', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-monthly_listeners', 'stage_name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.PositiveIntegerField(blank=True, help_text='Timestamp in track (seconds) for time-based comments', null=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='creator.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='creator.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowArtist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('followed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='creator.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_artists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-followed_at'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('album_type', models.CharField(choices=[('album', 'Album'), ('ep', 'EP'), ('mixtape', 'Mixtape')], default='album', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_art', models.ImageField(upload_to='albums/covers/')),
                ('release_date', models.DateField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('upc', models.CharField(blank=True, help_text='Universal Product Code', max_length=13, null=True, unique=True)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('is_explicit', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='creator.artist')),
                ('genres', models.ManyToManyField(related_name='albums', to='creator.genre')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='LikedAlbum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='creator.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-liked_at'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='playlists/covers/')),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', max_length=20)),
                ('is_collaborative', models.BooleanField(default=False)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('total_duration', models.PositiveIntegerField(default=0, help_text='Total duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborative_playlists', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowPlaylist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('followed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_playlists', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='creator.playlist')),
            ],
            options={
                'ordering': ['-followed_at'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='podcasts/covers/')),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_explicit', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True, null=True)),
                ('rss_feed', models.URLField(blank=True, null=True)),
                ('subscriber_count', models.PositiveIntegerField(default=0)),
                ('total_episodes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(related_name='podcasts', to='creator.genre')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='creator.artist')),
            ],
            options={
                'ordering': ['-subscriber_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LikedPodcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_podcasts', to=settings.AUTH_USER_MODEL)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='creator.podcast')),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('content_type', models.CharField(choices=[('music', 'Music'), ('podcast', 'Podcast Episode')], default='music', max_length=20)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tracks/original/')),
                ('hls_manifest', models.FileField(blank=True, null=True, upload_to='tracks/hls/')),
                ('hls_processed', models.BooleanField(default=False)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('isrc', models.CharField(blank=True, help_text='International Standard Recording Code', max_length=12, null=True, unique=True)),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='tracks/covers/')),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Processing (HLS)'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_explicit', models.BooleanField(default=False)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='creator.artist')),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_tracks', to='creator.artist')),
                ('genres', models.ManyToManyField(blank=True, related_name='tracks', to='creator.genre')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='creator.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_playlists', to='creator.track')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(db_index=True, help_text="Language code (e.g., 'en', 'es', 'fr')", max_length=10)),
                ('content', models.TextField(help_text='Lyrics content with timestamps if available')),
                ('is_synced', models.BooleanField(default=False, help_text='Whether lyrics have timestamps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='creator.track')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('played_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_played', models.PositiveIntegerField(help_text='Duration played in seconds')),
                ('completed', models.BooleanField(default=False, help_text='Whether track was played to completion')),
                ('source', models.CharField(blank=True, help_text='Where track was played from (playlist, album, etc.)', max_length=50, null=True)),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='creator.track')),
            ],
            options={
                'verbose_name_plural': 'Listening histories',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='LikedTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_tracks', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='creator.track')),
            ],
            options={
                'ordering': ['-liked_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='creator.track'),
        ),
        migrations.CreateModel(
            name='TrackDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('release_type', models.CharField(choices=[('single', 'Single'), ('album', 'Album'), ('ep', 'EP'), ('mixtape', 'Mixtape'), ('episode', 'Podcast Episode')], db_index=True, max_length=20)),
                ('album_name', models.CharField(blank=True, max_length=255, null=True)),
                ('track_number', models.PositiveIntegerField(blank=True, null=True)),
                ('disc_number', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('total_tracks', models.PositiveIntegerField(blank=True, null=True)),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True)),
                ('season_number', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('producer', models.CharField(blank=True, max_length=255, null=True)),
                ('composer', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('podcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='creator.podcast')),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='creator.track')),
            ],
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['stage_name'], name='creator_art_stage_n_017182_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['-monthly_listeners'], name='creator_art_monthly_38a670_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['comment', '-created_at'], name='creator_com_comment_1efaf1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AddIndex(
            model_name='followartist',
            index=models.Index(fields=['user', '-followed_at'], name='creator_fol_user_id_e2c3c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='followartist',
            unique_together={('user', 'artist')},
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist', '-release_date'], name='creator_alb_artist__de4863_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['-play_count'], name='creator_alb_play_co_3c458e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('artist', 'title')},
        ),
        migrations.AddIndex(
            model_name='likedalbum',
            index=models.Index(fields=['user', '-liked_at'], name='creator_lik_user_id_387539_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='likedalbum',
            unique_together={('user', 'album')},
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', '-created_at'], name='creator_pla_user_id_f62e43_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['privacy', '-follower_count'], name='creator_pla_privacy_4f00d0_idx'),
        ),
        migrations.AddIndex(
            model_name='followplaylist',
            index=models.Index(fields=['user', '-followed_at'], name='creator_fol_user_id_ceb533_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='followplaylist',
            unique_together={('user', 'playlist')},
        ),
        migrations.AddIndex(
            model_name='likedpodcast',
            index=models.Index(fields=['user', '-subscribed_at'], name='creator_lik_user_id_52cffd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='likedpodcast',
            unique_together={('user', 'podcast')},
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['content_type', 'status'], name='creator_tra_content_13cf0e_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['-play_count'], name='creator_tra_play_co_5ce5e9_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['-created_at'], name='creator_tra_created_78cbb7_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['artist', '-created_at'], name='creator_tra_artist__f69df0_idx'),
        ),
        migrations.AddIndex(
            model_name='playlisttrack',
            index=models.Index(fields=['playlist', 'position'], name='creator_pla_playlis_3982f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together={('playlist', 'track')},
        ),
        migrations.AddIndex(
            model_name='lyric',
            index=models.Index(fields=['track', 'language'], name='creator_lyr_track_i_374d99_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lyric',
            unique_together={('track', 'language')},
        ),
        migrations.AddIndex(
            model_name='listeninghistory',
            index=models.Index(fields=['user', '-played_at'], name='creator_lis_user_id_71fc09_idx'),
        ),
        migrations.AddIndex(
            model_name='listeninghistory',
            index=models.Index(fields=['track', '-played_at'], name='creator_lis_track_i_4aa591_idx'),
        ),
        migrations.AddIndex(
            model_name='likedtrack',
            index=models.Index(fields=['user', '-liked_at'], name='creator_lik_user_id_e3c6bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='likedtrack',
            unique_together={('user', 'track')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['track', '-created_at'], name='creator_com_track_i_4acecd_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='creator_com_user_id_37f34f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', '-created_at'], name='creator_com_parent__8c6474_idx'),
        ),
        migrations.AddIndex(
            model_name='trackdetail',
            index=models.Index(fields=['release_type', 'album_name'], name='creator_tra_release_af72c0_idx'),
        ),
        migrations.AddIndex(
            model_name='trackdetail',
            index=models.Index(fields=['podcast', 'episode_number'], name='creator_tra_podcast_75f4c8_idx'),
        ),
    ]
