# Generated by Django 5.2.4 on 2025-11-22 07:23

import django.core.validators
import mwonya_apps.creator.utils.file_handlers
import mwonya_apps.creator.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='album',
            name='creator_alb_artist__de4863_idx',
        ),
        migrations.RemoveIndex(
            model_name='album',
            name='creator_alb_play_co_3c458e_idx',
        ),
        migrations.RemoveIndex(
            model_name='artist',
            name='creator_art_stage_n_017182_idx',
        ),
        migrations.RemoveIndex(
            model_name='artist',
            name='creator_art_monthly_38a670_idx',
        ),
        migrations.RemoveIndex(
            model_name='playlist',
            name='creator_pla_user_id_f62e43_idx',
        ),
        migrations.RemoveIndex(
            model_name='playlist',
            name='creator_pla_privacy_4f00d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='track',
            name='creator_tra_content_13cf0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='track',
            name='creator_tra_play_co_5ce5e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='track',
            name='creator_tra_created_78cbb7_idx',
        ),
        migrations.RemoveIndex(
            model_name='track',
            name='creator_tra_artist__f69df0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.ImageField(storage=mwonya_apps.creator.utils.storage.ImageStorage(), upload_to=mwonya_apps.creator.utils.file_handlers.album_cover_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='album',
            name='upc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=mwonya_apps.creator.utils.storage.ImageStorage(), upload_to=mwonya_apps.creator.utils.file_handlers.artist_cover_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=mwonya_apps.creator.utils.storage.ImageStorage(), upload_to=mwonya_apps.creator.utils.file_handlers.artist_profile_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=mwonya_apps.creator.utils.storage.ImageStorage(), upload_to=mwonya_apps.creator.utils.file_handlers.playlist_cover_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='total_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover_image',
            field=models.ImageField(storage=mwonya_apps.creator.utils.storage.ImageStorage(), upload_to=mwonya_apps.creator.utils.file_handlers.podcast_cover_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Original uploaded audio file', null=True, storage=mwonya_apps.creator.utils.storage.RawAudioStorage(), upload_to=mwonya_apps.creator.utils.file_handlers.generate_track_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'm4a', 'wav', 'flac', 'aac', 'ogg'])]),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, storage=mwonya_apps.creator.utils.storage.ImageStorage(), upload_to=mwonya_apps.creator.utils.file_handlers.track_cover_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='track',
            name='hls_manifest',
            field=models.CharField(blank=True, help_text='Relative path to HLS manifest file', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='isrc',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
